##############
### dev
##############

server:
 port: 8080 

spring: 
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - sa-cluster-kafka-bootstrap:9092

          configuration:
            security:
              protocol: SASL_PLAINTEXT
            sasl:
              mechanism: SCRAM-SHA-512
              jaas:
                config: org.apache.kafka.common.security.scram.ScramLoginModule required username="order-user" password="Kfix1IkttbDa";
      
      bindings:
        boardCreate-out-0:
          destination: order-board-create
        boardUpdate-out-0:
          destination: order-board-update
        boardDelete-out-0:
          destination: order-board-delete
        

